# **Binary class classification problem**

5 input in 1 neurone (sigmoid) ---> output

In [ ]:
# create model class
import torch
import torch.nn as nn

In [ ]:
class Model(nn.Module):
  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    out = self.linear(x)
    out = self.sigmoid(x)
    return out


In [ ]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.6833, 0.7071, 0.5665, 0.5073, 0.7118],
        [0.6877, 0.6575, 0.7214, 0.5235, 0.5017],
        [0.5442, 0.7135, 0.6143, 0.6639, 0.5370],
        [0.5211, 0.5512, 0.6077, 0.5938, 0.6982],
        [0.5207, 0.5191, 0.7093, 0.6046, 0.6770],
        [0.7064, 0.5842, 0.5524, 0.6885, 0.6849],
        [0.5467, 0.5204, 0.6751, 0.5312, 0.5042],
        [0.5516, 0.6516, 0.6235, 0.6889, 0.5389],
        [0.6147, 0.7078, 0.7016, 0.7085, 0.5778],
        [0.6176, 0.6182, 0.6698, 0.5822, 0.5969]])

In [ ]:
model.linear.weight

Parameter containing:
tensor([[-0.3348,  0.0754, -0.1817, -0.0370, -0.4400]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.1998], requires_grad=True)

In [ ]:
# if we want to visualize the model properly like we do in sklearn
!pip install torchinfo


In [ ]:
from torchinfo import summary

In [ ]:
summary(model, input_size= (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 5]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 5]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# **Now let's create a complex NN using hidden layers**

1. 5 Inputs  
2. 3 neurone in 1st layer (with relu activation function)
3. then in second layer 1 neurone with (sigmoid activation function )


In [ ]:
# create a model class
class Model2(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.layer1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.layer2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.layer1(features)
    out = self.relu(out)
    out = self.layer2(out)
    out = self.sigmoid(out)
    return out



In [ ]:
# create a dummy dataset
features = torch.rand(10,5)

# create a model
model = Model2(features.shape[1])

# call the forward pass
model(features)

tensor([[0.5852],
        [0.5721],
        [0.6055],
        [0.6124],
        [0.5472],
        [0.5766],
        [0.6041],
        [0.5983],
        [0.5962],
        [0.5891]], grad_fn=<SigmoidBackward0>)

In [ ]:
print(model.layer1.weight)
print(model.layer2.weight)
print(model.layer1.bias)
print(model.layer2.bias)


Parameter containing:
tensor([[-0.2505, -0.2575, -0.3643, -0.4181, -0.0054],
        [ 0.3401,  0.2825,  0.3730,  0.2440,  0.3132],
        [-0.2877, -0.0532,  0.0726, -0.2143,  0.0533]], requires_grad=True)
Parameter containing:
tensor([[-0.3742,  0.3672,  0.2593]], requires_grad=True)
Parameter containing:
tensor([-0.2356, -0.1341, -0.0379], requires_grad=True)
Parameter containing:
tensor([0.1260], requires_grad=True)


In [ ]:
model.layer2.weight

Parameter containing:
tensor([[-0.3742,  0.3672,  0.2593]], requires_grad=True)

In [ ]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# **Simplified Structure**
using sequential container


In [ ]:
# create class
class Model3(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out



In [ ]:
# create a dummy dataset
features = torch.rand(10,5)

# define model
model = Model3(features.shape[1])

# call forwardpass
model(features)

tensor([[0.4582],
        [0.4665],
        [0.4442],
        [0.4603],
        [0.4743],
        [0.4424],
        [0.4717],
        [0.4533],
        [0.4539],
        [0.4563]], grad_fn=<SigmoidBackward0>)

In [ ]:
print(model.network[0].weight)
print(model.network[2].weight)

Parameter containing:
tensor([[-0.2818,  0.1767,  0.4294, -0.1194, -0.0712],
        [ 0.2642, -0.3858,  0.2771,  0.3284, -0.1518],
        [-0.0599,  0.2003, -0.2858, -0.1711,  0.4415]], requires_grad=True)
Parameter containing:
tensor([[0.4924, 0.5390, 0.1819]], requires_grad=True)


# **Let's Optimize the privous notebook (using the current notebook(sequential))**

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelEncoder

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [ ]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.drop(columns = ['id','Unnamed: 32'],inplace = True)

In [ ]:
df.sample(3)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
412         B        9.397         21.68           59.75      268.8   
170         B       12.320         12.39           78.85      464.1   
527         B       12.340         12.27           78.94      468.5   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
412          0.07969           0.06053         0.03735             0.005128   
170          0.10280           0.06981         0.03987             0.037000   
527          0.09003           0.06307         0.02958             0.026470   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
412         0.1274  ...         9.965          27.99            66.61   
170         0.1959  ...        13.500          15.64            86.97   
527         0.1689  ...        13.610          19.27            87.22   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
412       301.0            0.1086             0.1887           0.1868   
170       549.1            0.1385             0.1266           0.1242   
527       564.9            0.1292             0.2074           0.1791   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
412               0.02564          0.2376                  0.09206  
170               0.09391          0.2827                  0.06771  
527               0.10700          0.3110                  0.07592  

[3 rows x 31 columns]

**Train_Test_Split**

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns = ['diagnosis']), df['diagnosis'], test_size=0.2, random_state=42)

Standard Scaler

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

Label Encoder

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

#  **Numpy array to PyTorch Tensors**

since we were working with the numpy array and now we are working with PyTorch so we need pytorch tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
# from array to tensors
X_train_tensor

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64)

In [ ]:
print("Shape of X-train (Numpy array)",X_train.shape)
print("Shape of X_train_tensor (Pytorch Tensor)",X_train_tensor.shape)

print()

# shape of y_train
print("Shape of y_train",y_train.shape)
print("Shape of y_train_tensor",y_train_tensor.shape)


Shape of X-train (Numpy array) (455, 30)
Shape of X_train_tensor (Pytorch Tensor) torch.Size([455, 30])

Shape of y_train (455,)
Shape of y_train_tensor torch.Size([455])


# Defining Model

In [ ]:
class MySimpleNN(nn.Module):
  def __init__(self,num_feature):

    super().__init__()
    self.linear = nn.Linear(num_feature,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,x):
    out = self.linear(x.float()) # Cast input to float
    out = self.sigmoid(out) # Apply sigmoid to the output of the linear layer
    return out


  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y.float() * torch.log(y_pred) + (1 - y.float()) * torch.log(1 - y_pred)).mean() # Use the passed y argument
    return loss

In [ ]:
learning_rate = 0.1
epochs = 25

# Training Pipelines

In [ ]:
# create a model
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad


  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6967363357543945
Epoch: 2, Loss: 0.693906843662262
Epoch: 3, Loss: 0.6916161179542542
Epoch: 4, Loss: 0.6896547675132751
Epoch: 5, Loss: 0.6879134178161621
Epoch: 6, Loss: 0.686333179473877
Epoch: 7, Loss: 0.6848804950714111
Epoch: 8, Loss: 0.6835349798202515
Epoch: 9, Loss: 0.6822826266288757
Epoch: 10, Loss: 0.6811137199401855
Epoch: 11, Loss: 0.6800197958946228
Epoch: 12, Loss: 0.6789947748184204
Epoch: 13, Loss: 0.6780327558517456
Epoch: 14, Loss: 0.6771287322044373
Epoch: 15, Loss: 0.6762785315513611
Epoch: 16, Loss: 0.6754780411720276
Epoch: 17, Loss: 0.674723744392395
Epoch: 18, Loss: 0.6740123629570007
Epoch: 19, Loss: 0.6733410358428955
Epoch: 20, Loss: 0.6727070212364197
Epoch: 21, Loss: 0.672107994556427
Epoch: 22, Loss: 0.6715414524078369
Epoch: 23, Loss: 0.6710055470466614
Epoch: 24, Loss: 0.6704981923103333
Epoch: 25, Loss: 0.6700177192687988


**Evaluation**

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6163434982299805


# **Some Optimization**
1. will change the loss function with the torch built-in loss function

2. second we will change the optimizer with the torch built-in otimizer


**Define The Model**

In [ ]:
class MySimpleNN(nn.Module):
  def __init__(self,num_feature):

    super().__init__()
    self.linear = nn.Linear(num_feature,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,x):
    out = self.linear(x.float()) # Cast input to float
    out = self.sigmoid(out) # Apply sigmoid to the output of the linear layer
    return out


In [ ]:
learning_Rate = 0.1

In [ ]:
# 1st optimization (built-in loss function)
loss_function = nn.BCELoss()

**Teaining Pipeline**

In [ ]:
# create a model
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  # will change the model.loss_function with simple loss_function
  loss = loss_function(y_pred, y_train_tensor.unsqueeze(1).float())

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad


  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 1.0483537912368774
Epoch: 2, Loss: 0.7137418985366821
Epoch: 3, Loss: 0.5393312573432922
Epoch: 4, Loss: 0.44490620493888855
Epoch: 5, Loss: 0.3867745101451874
Epoch: 6, Loss: 0.34725984930992126
Epoch: 7, Loss: 0.318459153175354
Epoch: 8, Loss: 0.2963809370994568
Epoch: 9, Loss: 0.27880558371543884
Epoch: 10, Loss: 0.26440301537513733
Epoch: 11, Loss: 0.2523277997970581
Epoch: 12, Loss: 0.24201638996601105
Epoch: 13, Loss: 0.23307816684246063
Epoch: 14, Loss: 0.22523319721221924
Epoch: 15, Loss: 0.21827533841133118
Epoch: 16, Loss: 0.21204903721809387
Epoch: 17, Loss: 0.20643459260463715
Epoch: 18, Loss: 0.20133794844150543
Epoch: 19, Loss: 0.1966843158006668
Epoch: 20, Loss: 0.19241315126419067
Epoch: 21, Loss: 0.18847499787807465
Epoch: 22, Loss: 0.18482892215251923
Epoch: 23, Loss: 0.18144066631793976
Epoch: 24, Loss: 0.17828138172626495
Epoch: 25, Loss: 0.17532654106616974


In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5323176383972168


# 2nd change
# will use built-in optimizer

In [ ]:
# create a model
model = MySimpleNN(X_train_tensor.shape[1])

# define the optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  # will change the model.loss_function with simple loss_function
  loss = loss_function(y_pred, y_train_tensor.unsqueeze(1).float())


  # zero gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update


  # with torch.no_grad():
  #   model.linear.weight -= learning_rate * model.linear.weight.grad
  #   model.linear.bias -= learning_rate * model.linear.bias.grad
  optimizer.step()


  # # zero gradients
  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6447070240974426
Epoch: 2, Loss: 0.4961724281311035
Epoch: 3, Loss: 0.4155270457267761
Epoch: 4, Loss: 0.3649763762950897
Epoch: 5, Loss: 0.3300383985042572
Epoch: 6, Loss: 0.30426087975502014
Epoch: 7, Loss: 0.2843320667743683
Epoch: 8, Loss: 0.2683735191822052
Epoch: 9, Loss: 0.2552395761013031
Epoch: 10, Loss: 0.2441912442445755
Epoch: 11, Loss: 0.23473048210144043
Epoch: 12, Loss: 0.2265091836452484
Epoch: 13, Loss: 0.21927641332149506
Epoch: 14, Loss: 0.21284668147563934
Epoch: 15, Loss: 0.20707978308200836
Epoch: 16, Loss: 0.20186747610569
Epoch: 17, Loss: 0.1971249133348465
Epoch: 18, Loss: 0.19278448820114136
Epoch: 19, Loss: 0.18879155814647675
Epoch: 20, Loss: 0.18510150909423828
Epoch: 21, Loss: 0.18167738616466522
Epoch: 22, Loss: 0.1784883737564087
Epoch: 23, Loss: 0.1755084991455078
Epoch: 24, Loss: 0.1727156639099121
Epoch: 25, Loss: 0.1700909435749054


In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5280086398124695
