In [ ]:
# Tensors

In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"Using Gpu: {torch.cuda.get_device_name(0)}")
else:
    device = torch.device("cpu")
print(device)

Using Gpu: Tesla T4
cuda


In [ ]:
# empty tensor

a = torch.empty(2,3)

In [ ]:
#check type
type(a)

torch.Tensor

In [ ]:
#using Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using random
torch.rand(2,3)

tensor([[0.5150, 0.7847, 0.1870],
        [0.1540, 0.2760, 0.1512]])

In [ ]:
# using of seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arrange ->", torch.arange(0,10,2))

# using linspace
print("using linspace -> ", torch.linspace(0,10,10))

# using eye
print("using eye -> ", torch.eye(5))

# using full
print("using full -> ",torch.full((3,3),45))

using arrange -> tensor([0, 2, 4, 6, 8])
using linspace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[45, 45, 45],
        [45, 45, 45],
        [45, 45, 45]])


**Tensor** **Shapes**

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
# if i wanna create same shape tensor like as x then,
y = torch.empty_like(x)
y

tensor([[0, 0, 0],
        [0, 1, 0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
# rand generate number using float and in x variable we have int
# torch.rand_like(x)  --> will through error


# **Tensor** **Data** **Types**

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1,2,3], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# converting existing variable data type
x.to(torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [ ]:
torch.rand_like(x,dtype = torch.float64)

tensor([[0.0526, 0.5262, 0.4768],
        [0.9552, 0.9288, 0.0835]], dtype=torch.float64)

***Mathmatical operations***

1. Scalar operation

In [ ]:
x = torch.rand(2,3)
x

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])

In [ ]:
# addition
x + 2

tensor([[2.2666, 2.6274, 2.2696],
        [2.4414, 2.2969, 2.8317]])

In [ ]:
# subtraction
x - 2

tensor([[-1.7334, -1.3726, -1.7304],
        [-1.5586, -1.7031, -1.1683]])

In [ ]:
# multiplication

x * 3

tensor([[0.7997, 1.8823, 0.8089],
        [1.3241, 0.8908, 2.4951]])

In [ ]:
# division

x / 2

tensor([[0.1333, 0.3137, 0.1348],
        [0.2207, 0.1485, 0.4158]])

In [ ]:
# int divsion
(x * 100)/2

tensor([[13.3290, 31.3725, 13.4816],
        [22.0682, 14.8460, 41.5843]])

In [ ]:
# mod
((x * 100) // 2)

tensor([[13., 31., 13.],
        [22., 14., 41.]])

In [ ]:
# power

x**2

tensor([[0.0711, 0.3937, 0.0727],
        [0.1948, 0.0882, 0.6917]])

**2. Element wise operation**

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])
tensor([[0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])


In [ ]:
# add

a + b

tensor([[1.0569, 0.3448, 1.2448],
        [0.7826, 0.8848, 0.8151]])

In [ ]:
# sub
a - b

tensor([[-0.8462,  0.1942, -0.5272],
        [-0.3838,  0.2095, -0.8028]])

In [ ]:
# multiply
a  * b

tensor([[0.1002, 0.0203, 0.3179],
        [0.1163, 0.1848, 0.0050]])

In [ ]:
# division
a / b

tensor([[0.1107, 3.5806, 0.4050],
        [0.3418, 1.6206, 0.0076]])

In [ ]:
# power
a**b

tensor([[0.1174, 0.9060, 0.4033],
        [0.3904, 0.8158, 0.0163]])

In [ ]:
# mod
a % b

tensor([[0.1053, 0.0437, 0.3588],
        [0.1994, 0.2095, 0.0062]])

In [ ]:
c = torch.tensor([[1,-2,3],[-4,-5,6]])
d = torch.tensor([[1.9,2.5,4.8],[4.5,6.5,8.9]])

print(c)
print(d)

tensor([[ 1, -2,  3],
        [-4, -5,  6]])
tensor([[1.9000, 2.5000, 4.8000],
        [4.5000, 6.5000, 8.9000]])


In [ ]:
# abs
torch.abs(c)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# negative
torch.neg(c)

tensor([[-1,  2, -3],
        [ 4,  5, -6]])

In [ ]:
#round
torch.round(d)

tensor([[2., 2., 5.],
        [4., 6., 9.]])

In [ ]:
# ceil
torch.ceil(d)

tensor([[2., 3., 5.],
        [5., 7., 9.]])

In [ ]:
# floor
torch.floor(d)

tensor([[1., 2., 4.],
        [4., 6., 8.]])

In [ ]:
# clamp
# In the example, torch.clamp(d, min=6, max=8) replaces any value in tensor d
# below 6 with 6, and any value above 8 with 8.
torch.clamp(d,min = 6, max = 8 )

tensor([[6.0000, 6.0000, 6.0000],
        [6.0000, 6.5000, 8.0000]])

**Reduction operation**

In [ ]:
e = torch.randint(size=(2,3),low = 0, high = 10, dtype = torch.float32)
e

tensor([[9., 6., 2.],
        [0., 6., 2.]])

In [ ]:
# sum
torch.sum(e)


tensor(25.)

In [ ]:
# sum along rows
torch.sum(e,dim = 0)


tensor([ 9., 12.,  4.])

In [ ]:
# sum along columns
torch.sum(e, dim = 1)

tensor([17.,  8.])

In [ ]:
# mean
torch.mean(e)

tensor(4.1667)

In [ ]:
# means along col
torch.mean(e, dim = 0)

tensor([4.5000, 6.0000, 2.0000])

In [ ]:
# mean along rows
torch.mean(e, dim = 1)

tensor([5.6667, 2.6667])

In [ ]:
# median
torch.median(e)

tensor(2.)

In [ ]:
# median along col
torch.median(e, dim = 0)

torch.return_types.median(
values=tensor([0., 6., 2.]),
indices=tensor([1, 0, 0]))

In [ ]:
# median along rows
torch.median(e, dim = 1)

torch.return_types.median(
values=tensor([6., 2.]),
indices=tensor([1, 2]))

In [ ]:
# max
torch.max(e)

tensor(9.)

In [ ]:
#min
torch.min(e)

tensor(0.)

In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
# standard deviation
torch.std(e)

tensor(3.3714)

In [ ]:
# variance
torch.var(e)

tensor(11.3667)

In [ ]:
# argmin
torch.argmin(e)

tensor(3)

In [ ]:
# argmax
torch.argmax(e)

tensor(0)

# **Matrix operation**

In [ ]:
f = torch.randint(size=(2,3),low = 0, high = 10, dtype = torch.float32)
g = torch.randint(size=(3,2),low = 0, high = 10, dtype = torch.float32)

print(f)
print(g)

tensor([[7., 9., 7.],
        [3., 3., 4.]])
tensor([[3., 7.],
        [0., 9.],
        [0., 9.]])


In [ ]:
# matrix multiplication
torch.matmul(f,g)

tensor([[ 21., 193.],
        [  9.,  84.]])

In [ ]:

vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])


In [ ]:
# dot product
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f,0,1)

tensor([[7., 3.],
        [9., 3.],
        [7., 4.]])

In [ ]:
h = torch.randint(size=(3,3),low = 0, high = 10, dtype = torch.float32)
print(h)

tensor([[6., 9., 5.],
        [4., 8., 8.],
        [6., 0., 0.]])


In [ ]:
# determinant
torch.det(h)

tensor(192.0000)

In [ ]:
# inverse
torch.inverse(h)

tensor([[ 0.0000,  0.0000,  0.1667],
        [ 0.2500, -0.1563, -0.1458],
        [-0.2500,  0.2813,  0.0625]])

**Comparison Operation**

In [ ]:
i = torch.randint(size=(2,3),low = 0, high = 10)
i


tensor([[0, 0, 1],
        [3, 0, 1]])

In [ ]:
# greater than
torch.gt(i,5)


tensor([[False, False, False],
        [False, False, False]])

In [ ]:
# less than
torch.lt(i,5)

tensor([[True, True, True],
        [True, True, True]])

In [ ]:
# equal to
torch.eq(i,5)

tensor([[False, False, False],
        [False, False, False]])

In [ ]:
# not equal to
torch.ne(i,5)

tensor([[True, True, True],
        [True, True, True]])

In [ ]:
# greater than equal to
torch.ge(i,5)

tensor([[False, False, False],
        [False, False, False]])

In [ ]:
# less than equal to
torch.le(i,5)

tensor([[True, True, True],
        [True, True, True]])

# ***Special functions***

In [ ]:
j = torch.randint(size=(2,3),low = 0, high = 10)
j

tensor([[1, 7, 9],
        [4, 3, 8]])

In [ ]:
# log
torch.log(j)

tensor([[0.0000, 1.9459, 2.1972],
        [1.3863, 1.0986, 2.0794]])

In [ ]:
# exp
torch.exp(j)

tensor([[2.7183e+00, 1.0966e+03, 8.1031e+03],
        [5.4598e+01, 2.0086e+01, 2.9810e+03]])

In [ ]:
# sigmoid
torch.sigmoid(j)

tensor([[0.7311, 0.9991, 0.9999],
        [0.9820, 0.9526, 0.9997]])

In [ ]:
# sqrt
torch.sqrt(j)

tensor([[1.0000, 2.6458, 3.0000],
        [2.0000, 1.7321, 2.8284]])

In [ ]:
k = torch.randint(size=(2,3),low = 0, high = 10,dtype = torch.float32)
k

tensor([[9., 3., 7.],
        [8., 1., 4.]])

In [ ]:
# softmax --> supports only float
torch.softmax(k,dim = 0)

tensor([[0.7311, 0.8808, 0.9526],
        [0.2689, 0.1192, 0.0474]])

In [ ]:
# relu
torch.relu(k)

tensor([[9., 3., 7.],
        [8., 1., 4.]])

**Inplace Operations**

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.1591, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860]])
tensor([[0.1115, 0.2477, 0.6524],
        [0.6057, 0.3725, 0.7980]])


In [ ]:
# will take extra memory to store the reults of operation
m + n

tensor([[0.2707, 1.0130, 0.9503],
        [1.4092, 0.7539, 1.5841]])

In [ ]:
# what if i wanna add the results in m bcz i need m to perform operation
m.add_(n)

tensor([[0.2707, 1.0130, 0.9503],
        [1.4092, 0.7539, 1.5841]])

In [ ]:
m # changed m

tensor([[0.2707, 1.0130, 0.9503],
        [1.4092, 0.7539, 1.5841]])

In [ ]:
n # still same

tensor([[0.1115, 0.2477, 0.6524],
        [0.6057, 0.3725, 0.7980]])

# ***copying a tensor***

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.8399, 0.1374, 0.2331],
        [0.9578, 0.3313, 0.3227]])

In [ ]:
# copy
b = a.clone()

In [ ]:
b

tensor([[0.8399, 0.1374, 0.2331],
        [0.9578, 0.3313, 0.3227]])

In [ ]:
# same tensor but at different place
print(id(a))
print(id(b))


139424177000352
139424177001392


# **Tensor Operation on GPU**

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
# creating a new tensor on GPU
x = torch.rand(2,3).to(device)
x

tensor([[0.0162, 0.2137, 0.6249],
        [0.4340, 0.1371, 0.5117]], device='cuda:0')

In [ ]:
# moving an existing tensor to gpu
y = torch.rand(2,3)
y

tensor([[0.1585, 0.0758, 0.2247],
        [0.0624, 0.1816, 0.9998]])

In [ ]:
# y is on cpu and we wanna move it to gpu
y.to(device)

tensor([[0.1585, 0.0758, 0.2247],
        [0.0624, 0.1816, 0.9998]], device='cuda:0')

In [ ]:
y + 5

tensor([[5.1585, 5.0758, 5.2247],
        [5.0624, 5.1816, 5.9998]])

# ***CPU and GPU Comparison***

In [ ]:
# lets compare the CPU and GPU
import time

# Define the size of the matrices
size = 1000

# Create two random matrices on the CPU
matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

# Measure time on cpu
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) # matrix multiplication
end_time = time.time()
cpu_time = end_time - start_time

print(f"Time taken on CPU: {cpu_time} seconds")

# create two random matrices on the GPU
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

# measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
end_time = time.time()
gpu_time = end_time - start_time

print(f"Time taken on GPU: {gpu_time} seconds")


#compare results
print(f"\nSpeedup (CPU time / Gpu time): ", cpu_time/gpu_time)

Time taken on CPU: 0.027749300003051758 seconds
Time taken on GPU: 0.026342153549194336 seconds

Speedup (CPU time / Gpu time):  1.0534180491822567


# ***Reshaping tensors***

In [ ]:
z = torch.ones(4,4)
z

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
z.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
z.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
a = torch.rand(2,3,4)
a

tensor([[[0.9275, 0.5045, 0.6404, 0.4019],
         [0.9027, 0.9690, 0.6350, 0.6800],
         [0.7496, 0.0169, 0.4178, 0.1665]],

        [[0.3215, 0.6101, 0.4898, 0.5820],
         [0.7339, 0.6263, 0.3755, 0.3726],
         [0.1030, 0.3601, 0.8153, 0.5821]]])

In [ ]:
# permute
a.permute(2,0,1)

tensor([[[0.9275, 0.9027, 0.7496],
         [0.3215, 0.7339, 0.1030]],

        [[0.5045, 0.9690, 0.0169],
         [0.6101, 0.6263, 0.3601]],

        [[0.6404, 0.6350, 0.4178],
         [0.4898, 0.3755, 0.8153]],

        [[0.4019, 0.6800, 0.1665],
         [0.5820, 0.3726, 0.5821]]])

In [ ]:
# unsqueeze
#  image size
b = torch.rand(255,255,3)

b

tensor([[[0.7492, 0.1128, 0.7135],
         [0.1258, 0.3031, 0.9084],
         [0.5866, 0.4363, 0.9337],
         ...,
         [0.1608, 0.9910, 0.5008],
         [0.6916, 0.4509, 0.6997],
         [0.8945, 0.2733, 0.9732]],

        [[0.8077, 0.7549, 0.4502],
         [0.5282, 0.7590, 0.3582],
         [0.0240, 0.3518, 0.5827],
         ...,
         [0.7964, 0.7734, 0.6668],
         [0.8207, 0.2240, 0.4196],
         [0.0355, 0.2346, 0.6942]],

        [[0.6462, 0.6461, 0.0230],
         [0.5885, 0.3538, 0.0101],
         [0.5472, 0.6346, 0.8549],
         ...,
         [0.9534, 0.2070, 0.0406],
         [0.4469, 0.1400, 0.1039],
         [0.1565, 0.3398, 0.3331]],

        ...,

        [[0.6862, 0.3483, 0.0976],
         [0.9418, 0.6332, 0.4979],
         [0.1428, 0.0962, 0.2368],
         ...,
         [0.3459, 0.0916, 0.7624],
         [0.1870, 0.1433, 0.4661],
         [0.3711, 0.9606, 0.3610]],

        [[0.4179, 0.9604, 0.2305],
         [0.8008, 0.4568, 0.5263],
         [0.

In [ ]:
b.unsqueeze(0).shape

torch.Size([1, 255, 255, 3])

In [ ]:
# squeeze
b.squeeze(1).shape

torch.Size([255, 255, 3])

In [ ]:
# comparison

# Create a tensor with dimensions of size 1
c = torch.tensor([[[1, 2, 3]]])
print("Original tensor shape:", c.shape)

# Squeeze the tensor
c_squeezed = torch.squeeze(c)
print("Squeezed tensor shape:", c_squeezed.shape)

# Squeeze a specific dimension
c_squeezed_dim = torch.squeeze(c, dim=0)
print("Squeezed at dim 0 shape:", c_squeezed_dim.shape)

Original tensor shape: torch.Size([1, 1, 3])
Squeezed tensor shape: torch.Size([3])
Squeezed at dim 0 shape: torch.Size([1, 3])


# **NumPy and PyTorch**

In [ ]:
import numpy as np


In [ ]:
d = torch.tensor([1,2,3])
d

tensor([1, 2, 3])

In [ ]:
# converting tensor to numpy
e = d.numpy()
e

array([1, 2, 3])

In [ ]:
type(e)

numpy.ndarray

In [ ]:
# converting numpy to tensor
torch.from_numpy(e)

tensor([1, 2, 3])