In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelEncoder

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [ ]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns = ['id','Unnamed: 32'],inplace = True)

In [ ]:
df.sample(3)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
174         B       10.660         15.15           67.49      349.6   
59          B        8.618         11.79           54.34      224.5   
217         B       10.200         17.48           65.05      321.2   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
174          0.08792           0.04302         0.00000             0.000000   
59           0.09752           0.05272         0.02061             0.007799   
217          0.08054           0.05907         0.05774             0.010710   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
174         0.1928  ...        11.540          19.20             73.2   
59          0.1683  ...         9.507          15.40             59.9   
217         0.1964  ...        11.480          24.47             75.4   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
174       408.3           0.10760            0.06791           0.0000   
59        274.9           0.17330            0.12390           0.1168   
217       403.7           0.09527            0.13970           0.1925   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
174               0.00000          0.2710                  0.06164  
59                0.04419          0.3220                  0.09026  
217               0.03571          0.2868                  0.07809  

[3 rows x 31 columns]

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

# **Train Test Split**

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns = ['diagnosis']), df['diagnosis'], test_size=0.2, random_state=42)

In [ ]:
y_test

204    B
70     M
131    M
431    B
540    B
      ..
486    B
75     M
249    B
238    B
265    M
Name: diagnosis, Length: 114, dtype: object

**Standard Scaler**

In [ ]:
scaler = StandardScaler()

In [ ]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

**Label Encoder**

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,

#  **Numpy array to PyTorch Tensors**

since we were working with the numpy array and now we are working with PyTorch so we need pytorch tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [ ]:
# from array to tensors
X_train_tensor

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64)

In [ ]:
print("Shape of X-train (Numpy array)",X_train.shape)
print("Shape of X_train_tensor (Pytorch Tensor)",X_train_tensor.shape)

print()

# shape of y_train
print("Shape of y_train",y_train.shape)
print("Shape of y_train_tensor",y_train_tensor.shape)


Shape of X-train (Numpy array) (455, 30)
Shape of X_train_tensor (Pytorch Tensor) torch.Size([455, 30])

Shape of y_train (455,)
Shape of y_train_tensor torch.Size([455])


# **Defining Model**

In [ ]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss





**Important parameter**

In [ ]:
learning_rate = 0.1
epochs = 25

# **Training Pipelines**

In [ ]:
# create a model
model = MySimpleNN(X_train_tensor)

In [ ]:
model.weights

tensor([[0.7197],
        [0.0484],
        [0.2440],
        [0.6661],
        [0.3359],
        [0.7494],
        [0.0229],
        [0.9292],
        [0.6587],
        [0.8372],
        [0.8849],
        [0.6437],
        [0.6301],
        [0.4654],
        [0.0341],
        [0.9903],
        [0.2485],
        [0.2200],
        [0.5538],
        [0.3459],
        [0.4608],
        [0.1476],
        [0.7350],
        [0.1904],
        [0.7163],
        [0.2602],
        [0.6807],
        [0.2621],
        [0.5955],
        [0.1929]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [ ]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epochs in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epochs + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.693144520394816
Epoch: 2, Loss: 3.562680749204508
Epoch: 3, Loss: 3.430998128529809
Epoch: 4, Loss: 3.293472511764265
Epoch: 5, Loss: 3.1490238733570934
Epoch: 6, Loss: 3.0007218473774766
Epoch: 7, Loss: 2.8472909488563967
Epoch: 8, Loss: 2.689515437803862
Epoch: 9, Loss: 2.526130378980325
Epoch: 10, Loss: 2.358195076527198
Epoch: 11, Loss: 2.1887208121874484
Epoch: 12, Loss: 2.0205817050326944
Epoch: 13, Loss: 1.8547799303430343
Epoch: 14, Loss: 1.6921577967825738
Epoch: 15, Loss: 1.5386264292191594
Epoch: 16, Loss: 1.3942185514230048
Epoch: 17, Loss: 1.2642220657564818
Epoch: 18, Loss: 1.1504933062523932
Epoch: 19, Loss: 1.0545243325579678
Epoch: 20, Loss: 0.9769618326480379
Epoch: 21, Loss: 0.9170566187062716
Epoch: 22, Loss: 0.8725323524661766
Epoch: 23, Loss: 0.8401679622011939
Epoch: 24, Loss: 0.8166772092250985


In [ ]:
model.weights

tensor([[ 0.4630],
        [-0.1071],
        [ 0.4968],
        [ 0.0209],
        [ 0.4295],
        [ 0.2455],
        [-0.3331],
        [-0.3207],
        [ 0.1978],
        [ 0.0832],
        [-0.1261],
        [ 0.6932],
        [-0.3302],
        [ 0.2658],
        [ 0.0139],
        [ 0.1811],
        [ 0.2717],
        [-0.0683],
        [-0.1246],
        [-0.0503],
        [ 0.2884],
        [ 0.4931],
        [-0.4248],
        [-0.3180],
        [-0.1093],
        [ 0.2187],
        [ 0.3604],
        [-0.6031],
        [-0.0820],
        [-0.1419]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([-0.1538], dtype=torch.float64, requires_grad=True)

# **Evaluation**

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5107725262641907
